// lib/poSampleData.ts

import { PurchaseOrder } from "@/app/types/po";

export const samplePOs: PurchaseOrder[] = [
  // EV Team Orders
  {
    id: "1",
    poNumber: "PO-2025-001",
    date: "2025-01-10",
    vendor: "Spark Motors",
    description: "Electric motor assembly components",
    category: "Powertrain",
    quantity: 5,
    unitCost: 1200,
    totalCost: 6000,
    requestedBy: "Alex Kim",
    status: "pending",
    subteam: "EV",
    expectedDelivery: "2025-02-05"
  },
  {
    id: "3",
    poNumber: "PO-2025-003",
    date: "2025-01-15",
    vendor: "Volt Systems",
    description: "High-voltage battery packs",
    category: "Powertrain",
    quantity: 2,
    unitCost: 4800,
    totalCost: 9600,
    requestedBy: "Ryan Patel",
    status: "approved",
    subteam: "EV",
    expectedDelivery: "2025-03-01"
  },
  {
    id: "7",
    poNumber: "PO-2025-007",
    date: "2025-02-01",
    vendor: "TechPower Solutions",
    description: "Battery management system (BMS)",
    category: "Electronics",
    quantity: 3,
    unitCost: 850,
    totalCost: 2550,
    requestedBy: "Alex Kim",
    status: "approved",
    subteam: "EV",
    expectedDelivery: "2025-02-25"
  },
  {
    id: "10",
    poNumber: "PO-2025-010",
    date: "2025-02-08",
    vendor: "Volt Systems",
    description: "Charging port assemblies",
    category: "Electronics",
    quantity: 4,
    unitCost: 320,
    totalCost: 1280,
    requestedBy: "Ryan Patel",
    status: "pending",
    subteam: "EV",
    expectedDelivery: "2025-03-10"
  },
  {
    id: "13",
    poNumber: "PO-2025-013",
    date: "2025-02-15",
    vendor: "Spark Motors",
    description: "Motor controller units",
    category: "Electronics",
    quantity: 2,
    unitCost: 1500,
    totalCost: 3000,
    requestedBy: "Alex Kim",
    status: "approved",
    subteam: "EV",
    expectedDelivery: "2025-03-15"
  },
  {
    id: "16",
    poNumber: "PO-2025-016",
    date: "2025-02-22",
    vendor: "WireTech Pro",
    description: "High-voltage wiring harness",
    category: "Electronics",
    quantity: 1,
    unitCost: 680,
    totalCost: 680,
    requestedBy: "Ryan Patel",
    status: "pending",
    subteam: "EV",
    expectedDelivery: "2025-03-20"
  },
  {
    id: "19",
    poNumber: "PO-2025-019",
    date: "2025-03-01",
    vendor: "TechPower Solutions",
    description: "Battery thermal management sensors",
    category: "Electronics",
    quantity: 12,
    unitCost: 45,
    totalCost: 540,
    requestedBy: "Alex Kim",
    status: "approved",
    subteam: "EV",
    expectedDelivery: "2025-03-25"
  },
  {
    id: "22",
    poNumber: "PO-2025-022",
    date: "2025-03-08",
    vendor: "Volt Systems",
    description: "Electric drivetrain components",
    category: "Powertrain",
    quantity: 6,
    unitCost: 920,
    totalCost: 5520,
    requestedBy: "Ryan Patel",
    status: "rejected",
    subteam: "EV",
  },
  {
    id: "25",
    poNumber: "PO-2025-025",
    date: "2025-03-15",
    vendor: "Spark Motors",
    description: "Regenerative braking system",
    category: "Powertrain",
    quantity: 1,
    unitCost: 2100,
    totalCost: 2100,
    requestedBy: "Alex Kim",
    status: "pending",
    subteam: "EV",
    expectedDelivery: "2025-04-10"
  },
  {
    id: "28",
    poNumber: "PO-2025-028",
    date: "2025-03-22",
    vendor: "TechPower Solutions",
    description: "Power inverter modules",
    category: "Electronics",
    quantity: 2,
    unitCost: 1350,
    totalCost: 2700,
    requestedBy: "Ryan Patel",
    status: "approved",
    subteam: "EV",
    expectedDelivery: "2025-04-15"
  },

  // IC Team Orders
  {
    id: "2",
    poNumber: "PO-2025-002",
    date: "2025-01-12",
    vendor: "FuelTech Supply",
    description: "Combustion engine mounts",
    category: "Chassis",
    quantity: 10,
    unitCost: 350,
    totalCost: 3500,
    requestedBy: "Maria Lopez",
    status: "pending",
    subteam: "IC",
    expectedDelivery: "2025-02-20"
  },
  {
    id: "4",
    poNumber: "PO-2025-004",
    date: "2025-01-18",
    vendor: "Precision Metals",
    description: "Frame reinforcement bars",
    category: "Chassis",
    quantity: 15,
    unitCost: 150,
    totalCost: 2250,
    requestedBy: "Daniel Park",
    status: "approved",
    subteam: "IC",
  },
  {
    id: "6",
    poNumber: "PO-2025-006",
    date: "2025-01-25",
    vendor: "AutoParts Central",
    description: "Brake calipers and rotors",
    category: "Chassis",
    quantity: 8,
    unitCost: 220,
    totalCost: 1760,
    requestedBy: "Noah Garcia",
    status: "rejected",
    subteam: "IC",
  },
  {
    id: "8",
    poNumber: "PO-2025-008",
    date: "2025-02-03",
    vendor: "PerformanceMax",
    description: "Turbocharger assembly",
    category: "Engine",
    quantity: 1,
    unitCost: 3200,
    totalCost: 3200,
    requestedBy: "Maria Lopez",
    status: "approved",
    subteam: "IC",
  },
  {
    id: "11",
    poNumber: "PO-2025-011",
    date: "2025-02-10",
    vendor: "FuelTech Supply",
    description: "High-performance fuel injectors",
    category: "Engine",
    quantity: 8,
    unitCost: 175,
    totalCost: 1400,
    requestedBy: "Daniel Park",
    status: "approved",
    subteam: "IC",
  },
  {
    id: "14",
    poNumber: "PO-2025-014",
    date: "2025-02-17",
    vendor: "AutoParts Central",
    description: "Suspension components kit",
    category: "Chassis",
    quantity: 1,
    unitCost: 2450,
    totalCost: 2450,
    requestedBy: "Noah Garcia",
    status: "pending",
    subteam: "IC",
  },
  {
    id: "17",
    poNumber: "PO-2025-017",
    date: "2025-02-24",
    vendor: "Precision Metals",
    description: "Exhaust system headers",
    category: "Engine",
    quantity: 2,
    unitCost: 680,
    totalCost: 1360,
    requestedBy: "Maria Lopez",
    status: "approved",
    subteam: "IC",
  },
  {
    id: "20",
    poNumber: "PO-2025-020",
    date: "2025-03-03",
    vendor: "PerformanceMax",
    description: "Engine cooling radiator",
    category: "Engine",
    quantity: 1,
    unitCost: 540,
    totalCost: 540,
    requestedBy: "Daniel Park",
    status: "approved",
    subteam: "IC",
  },
  {
    id: "23",
    poNumber: "PO-2025-023",
    date: "2025-03-10",
    vendor: "FuelTech Supply",
    description: "Performance air intake system",
    category: "Engine",
    quantity: 1,
    unitCost: 890,
    totalCost: 890,
    requestedBy: "Maria Lopez",
    status: "pending",
    subteam: "IC",
  },
  {
    id: "26",
    poNumber: "PO-2025-026",
    date: "2025-03-17",
    vendor: "AutoParts Central",
    description: "Racing brake pads set",
    category: "Chassis",
    quantity: 4,
    unitCost: 165,
    totalCost: 660,
    requestedBy: "Noah Garcia",
    status: "approved",
    subteam: "IC",
  },
  {
    id: "29",
    poNumber: "PO-2025-029",
    date: "2025-03-24",
    vendor: "Precision Metals",
    description: "Roll cage tubing",
    category: "Chassis",
    quantity: 20,
    unitCost: 85,
    totalCost: 1700,
    requestedBy: "Daniel Park",
    status: "pending",
    subteam: "IC",
  },
  {
    id: "31",
    poNumber: "PO-2025-031",
    date: "2025-03-28",
    vendor: "PerformanceMax",
    description: "High-flow fuel pump",
    category: "Engine",
    quantity: 1,
    unitCost: 425,
    totalCost: 425,
    requestedBy: "Maria Lopez",
    status: "approved",
    subteam: "IC",
  },

  // Admin Team Orders
  {
    id: "5",
    poNumber: "PO-2025-005",
    date: "2025-01-22",
    vendor: "Office Depot",
    description: "Marketing banners and printing materials",
    category: "Marketing",
    quantity: 25,
    unitCost: 40,
    totalCost: 1000,
    requestedBy: "Emma Johnson",
    status: "approved",
    subteam: "Admin",
    notes: "Needed for recruitment fair"
  },
  {
    id: "9",
    poNumber: "PO-2025-009",
    date: "2025-02-05",
    vendor: "Catering Plus",
    description: "Team meeting catering services",
    category: "Events",
    quantity: 1,
    unitCost: 320,
    totalCost: 320,
    requestedBy: "Sophia Chen",
    status: "approved",
    subteam: "Admin",
    notes: "Monthly all-hands meeting"
  },
  {
    id: "12",
    poNumber: "PO-2025-012",
    date: "2025-02-12",
    vendor: "PrintPro Graphics",
    description: "Team t-shirts and merchandise",
    category: "Marketing",
    quantity: 50,
    unitCost: 22,
    totalCost: 1100,
    requestedBy: "Emma Johnson",
    status: "pending",
    subteam: "Admin",
    notes: "Competition uniforms"
  },
  {
    id: "15",
    poNumber: "PO-2025-015",
    date: "2025-02-19",
    vendor: "Office Depot",
    description: "Office supplies and stationery",
    category: "Office",
    quantity: 1,
    unitCost: 245,
    totalCost: 245,
    requestedBy: "Sophia Chen",
    status: "approved",
    subteam: "Admin",
    notes: "Quarterly supply restock"
  },
  {
    id: "18",
    poNumber: "PO-2025-018",
    date: "2025-02-26",
    vendor: "TravelSmart",
    description: "Competition travel accommodations",
    category: "Travel",
    quantity: 15,
    unitCost: 180,
    totalCost: 2700,
    requestedBy: "Emma Johnson",
    status: "approved",
    subteam: "Admin",
    notes: "Hotel rooms for regional competition"
  },
  {
    id: "21",
    poNumber: "PO-2025-021",
    date: "2025-03-05",
    vendor: "Catering Plus",
    description: "Sponsor dinner event catering",
    category: "Events",
    quantity: 1,
    unitCost: 850,
    totalCost: 850,
    requestedBy: "Sophia Chen",
    status: "pending",
    subteam: "Admin",
    notes: "Annual sponsor appreciation"
  },
  {
    id: "24",
    poNumber: "PO-2025-024",
    date: "2025-03-12",
    vendor: "PrintPro Graphics",
    description: "Sponsorship display banners",
    category: "Marketing",
    quantity: 6,
    unitCost: 95,
    totalCost: 570,
    requestedBy: "Emma Johnson",
    status: "approved",
    subteam: "Admin",
    notes: "For pit area display"
  },
  {
    id: "27",
    poNumber: "PO-2025-027",
    date: "2025-03-19",
    vendor: "Office Depot",
    description: "Laptop and computer accessories",
    category: "Office",
    quantity: 3,
    unitCost: 420,
    totalCost: 1260,
    requestedBy: "Sophia Chen",
    status: "rejected",
    subteam: "Admin",
    notes: "Budget exceeded this quarter"
  },
  {
    id: "30",
    poNumber: "PO-2025-030",
    date: "2025-03-26",
    vendor: "TravelSmart",
    description: "National competition flight tickets",
    category: "Travel",
    quantity: 20,
    unitCost: 340,
    totalCost: 6800,
    requestedBy: "Emma Johnson",
    status: "pending",
    subteam: "Admin",
    notes: "Book 2 months in advance"
  },
  {
    id: "32",
    poNumber: "PO-2025-032",
    date: "2025-03-30",
    vendor: "PrintPro Graphics",
    description: "Recruitment posters and flyers",
    category: "Marketing",
    quantity: 200,
    unitCost: 3.50,
    totalCost: 700,
    requestedBy: "Sophia Chen",
    status: "approved",
    subteam: "Admin",
    notes: "Spring semester recruitment"
  },
];